### ISSUE TITLE
Add SIGMOD'22 to your publications

### ISSUE THREAD

**Issue by PanZaifeng** [wanweitao/wanweitao.github.io#1]
Congratulations! I've noticed that your excellent paper, "CompressDB: Enabling Efficient Compressed Data Direct Processing for Various Databases", has been accepted by SIGMOD'22.
But it seems that you have not updated the publication list on your homepage yet. Please update it so that everyone can know your excellent work!!!

**Comment by wanweitao** [comment]
Thanks for your kindly notification!
